### ISSUE TITLE
error to execute est_waterlevel.py

### ISSUE THREAD

**Issue by DavidChoi76** [xmlyqing00/V-FloodNet#1]
I'm following your execution description in README's Usage section of V-FloodNet github.
I prepared a video to test water depth estimation. Then there was no problem 2.1 and 2.2.
Then I got a error like below figures. I think the code can't find something.
Could you give me how to fix this error?

<img width="944" alt="error_1" src="https://user-images.githubusercontent.com/23341664/209923655-0450c5a2-8484-4ff2-a043-0e717aa0674b.png">
<img width="269" alt="error_2" src="https://user-images.githubusercontent.com/23341664/209923663-5df38682-4988-4b49-969b-08617a6a66ba.png">

**Comment by xmlyqing00** [comment]
Thank you for pointing it out. I'm gonna work on it this weekend.

**Comment by xmlyqing00** [comment]
Could you give the version of Detectron2. Maybe `condo list detectron2`.  I think the problem is from this package.

**Comment by xmlyqing00** [comment]
It's been a while since we heard from you regarding this issue. We value your feedback and would like to ensure your concerns are addressed. However, due to the extended period of inactivity, we are going to close this issue for now.

If you still experience this problem or have any further questions, please feel free to reopen it. We're here to help!
