### ISSUE TITLE
ModuleNotFoundError: No module named 'segmentation_models_pytorch.linknet'

### ISSUE THREAD

**Issue by Remotsensei** [xmlyqing00/V-FloodNet#2]
I tried installing the system, but i get this error when running the first step
pytorch is installed and if i load segmentation_models_pytorch it loads. but there appears to be no linket submodule

**Comment by xmlyqing00** [comment]
Hi,

Thanks for your interest in our work. It seems that your python environment isn't setup correctly. I checked the dependent packages and updated the installation instructions. I recommend you create a new python virtual environment and start over the installation again. Ubuntu or WSL2 is recommended. If you have any questions, you can post here with your pip environment.

Thanks

**Comment by xmlyqing00** [comment]
It's been a while since we heard from you regarding this issue. We value your feedback and would like to ensure your concerns are addressed. However, due to the extended period of inactivity, we are going to close this issue for now.

If you still experience this problem or have any further questions, please feel free to reopen it. We're here to help!
